services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - '127.0.0.1:${MONGO_PORT}:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nestjs-app:
    image: ghcr.io/manuelentrena/car-leadership:latest
    container_name: nestjs-app
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./logs:/var/www/app/logs
    networks:
      - app-network
    depends_on:
      - mongodb
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:
