services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - app-network
  nestjs-app:
    build:
      context: .
      dockerfile: docker/dockerfile.prod.yml
    container_name: nestjs-app
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - mongodb

networks:
  app-network:
    driver: bridge
    
volumes:
  mongo-data:
