# Install dependencies only when needed
FROM node:18-alpine3.15 AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Build the app with cache dependencies
FROM node:18-alpine3.15 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Production image, copy all the files and run next
FROM node:18-alpine3.15 AS runner
WORKDIR /var/www/app
COPY package.json package-lock.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
COPY ./.env ./
COPY ./public ./public
# Dar permiso para ejecutar la applicación
RUN adduser --disabled-password entrenadev
RUN chown -R entrenadev:entrenadev /var/www/app
USER entrenadev

EXPOSE ${PORT}

CMD [ "node","dist/main" ]